
project_id = "mnixymlfubqxxpwtqkqo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[functions]
[functions.send-appointment-notification]
verify_jwt = true
