// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnixymlfubqxxpwtqkqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaXh5bWxmdWJxeHhwd3Rxa3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTk3NzEsImV4cCI6MjA1NjQ5NTc3MX0.Gon5cy3bdyHZLBwSoYRCkGVmyYtHJeX1RyOmVP7YfUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);